// CP_OptoTrack.idl : IDL source for CP_OptoTrack.exe
//

// This file will be processed by the MIDL tool to
// produce the type library (CP_OptoTrack.tlb) and marshalling code.

import "oaidl.idl";
//import "ocidl.idl";


//------------------------------------------------------------
// IOptoTrack interface

	[
		object,  // tells MIDL to produce COM, not RPC interface
		uuid(ebd33078-ceb1-11d5-9c3e-0050da2a68c8),
		dual,
    oleautomation,
		helpstring("IOptoTrack Interface"),
 		pointer_default(unique)
	]                                  
	interface IOptoTrack  : IDispatch {

    [helpstring("Program Version String")] 
       HRESULT GetVersion([out] BSTR * pVal);

    [helpstring("Connects to tracker")] 
      HRESULT ConnectTracker();

    [helpstring("Disconnects from the tracker")] 
      HRESULT DisconnectTracker();

    [helpstring("Returns tracker ID: 0 = not connected, 1 = Liberty, 2 = OptoTrak, 3 = ISCAN. State: 1=connected")] 
      HRESULT GetTrackerState( [out] long * piTrackerID,
                               [out] long * piState   );

    [helpstring("Returns current frame count.")] 
      HRESULT GetFrameCount( [out] long * pnFrames );

    [helpstring("Time scale coefficients to convert frames to milliseconds")]
      HRESULT GetTimeScale([out] double *pdC0,
                           [out] double *pdC1);
    [helpstring("Time scale coefficients to convert frames to milliseconds")]
      HRESULT SetTimeScale([in] double dC0,
                           [in] double dC1);

    [helpstring("Rotation and translation matrix (3x4)")]
      HRESULT GetTransformMatrix([in, defaultvalue(1)] long iTransformIdx,
                                 [out] VARIANT * pvTransform);
    [helpstring("Rotation and translation matrix (3x4)")]
      HRESULT SetTransformMatrix([in] VARIANT vTransform,
                                 [in, defaultvalue(1)] long iTransformIdx);

		[helpstring("Array of sensors: index and port (optional)")] 
      HRESULT GetSensors([out] VARIANT *pvSensors);
 		[helpstring("Array of sensors: index and port (optional)")] 
      HRESULT SetSensors([in] VARIANT vSensors);

 		[helpstring("Activate markers. Ignored on Liberty.")]
      HRESULT ActivateSensors( );
 		[helpstring("Deactivate markers. Ignored on Liberty.")]
      HRESULT DeactivateSensors( );

		[helpstring("Array of sensors transform index")] 
      HRESULT GetSensorsTransformIdx([out] VARIANT *pvTransformIdx);
 		[helpstring("Array of sensors transform index")] 
      HRESULT SetSensorsTransformIdx([in] VARIANT vTransformIdx);

    [helpstring("Buffer size in frames")] 
      HRESULT GetBufferSize([out] long *pnFrames);
    [helpstring("Get latest data index")] 
      HRESULT GetDataIndexLatest( [out] long *piDataIdx );
    [helpstring("Get latest data index, timestamp in ms, and coordinates")] 
      HRESULT GetSensorLatest( [in] long iSensorIdx,
                               [in, defaultvalue(1)]  long nFrames,
                               [out] long *piDataIdx,
                               [out] VARIANT * pvTimeStampMs,
                               [out] VARIANT * pvCoord,
                               [out] VARIANT * pvVelocity );
    [helpstring("Get timestamps, and coordinates")] 
      HRESULT GetSensorBuffered( [in] long iSensorIdx,
                                 [in] long iDataIdx,
                                 [in] long nFrames,
                                 [out] VARIANT * pvTimeStampMs,
                                 [out] VARIANT * pvCoord,
                                 [out] VARIANT * pvVelocity );
    [helpstring("Get latest data index, timestamp, and coordinates")] 
      HRESULT GetAllSensorsLatest( [in, defaultvalue(1)]  long nFrames,
                                   [out] long *piIdx,
                                   [out] VARIANT * pvTimeStampMs,
                                   [out] VARIANT * pvCoord,
                                   [out] VARIANT * pvVelocity );
    [helpstring("Get timestamps, and coordinates")] 
      HRESULT GetAllSensorsBuffered( [in] long iDataIdx,
                                     [in] long nFrames,
                                     [out] VARIANT * pvTimeStampMs,
                                     [out] VARIANT * pvCoord,
                                     [out] VARIANT * pvVelocity );


  };


[
	// normally don't have to change this guid,
	// it's used to label the type library
	uuid(ebd33074-ceb1-11d5-9c3e-0050da2a68c8),
  // Note: make sure to update code in LoadRegTypeLib() and UnRegisterTypeLib()
  // on version change!
	version(0.0),  
	// this shows up in the "references" in VB
	helpstring("CP_OptoTrack Type Library")
]
library CP_OptoTrackLib  // This is the lib name used by VB
{
	importlib("stdole32.tlb");
	[
		// This is the class (com object guid)
		// Don't have to change it normally
		uuid(ebd33070-ceb1-11d5-9c3e-0050da2a68c8),
		helpstring("CP_OptoTrack Class")
	]

	coclass CP_OptoClass { // This is the object name used by VB
	
    [default] dispinterface IOptoTrack;
	};

};
