#include "ATL_Defs.h"            // ATL,COM and Windows definitions
#include "resource.h"            // Resource IDs for registry
#include "CP_Display.h"          // this file is generated by MIDL compiler
#include "VMouse.h"              // Uses ATL and IDs

#include "GL_Engine.h"
#include "Util\CP_printf.h"
#include "Util\SafeArrayLib.h"


//==============================================================================
CVMouse::CVMouse(){
}

//==============================================================================
CVMouse::~CVMouse(){
}

//==============================================================================
STDMETHODIMP CVMouse::GetShowFlag(long * piShowFlag){
  * piShowFlag = g_iMouseShowFlag;

  return S_OK;
}


//==============================================================================
STDMETHODIMP CVMouse::SetShowFlag(long iShowFlag){
  if( iShowFlag ) return Show();
  return Hide();
}

//==============================================================================
STDMETHODIMP CVMouse::GetXY(SAFEARRAY ** ppsaMtx){
  SAFEARRAY *psaMtx;
  int * piData;

  * ppsaMtx = NULL;
  if( g_MakeSafeArray( 2, &psaMtx, &piData ) ){
    return g_ErrorToHresult(1);
  }
  piData[0] = g_tMouseXY.x;
  piData[1] = g_tMouseXY.y;
  SafeArrayUnaccessData( psaMtx );
  * ppsaMtx = psaMtx;

  return S_OK;
}

//==============================================================================
STDMETHODIMP CVMouse::GetAllEvents(SAFEARRAY ** ppsaMtx){
  SAFEARRAY *psaMtx;
  int * piData;
  int iSize;

  * ppsaMtx = NULL;
  if( g_MakeSafeArray( 3, 3, &psaMtx, &piData ) ){
    return g_ErrorToHresult(1);
  }
  iSize = sizeof(g_aiMouseEvents);
  memcpy( piData, g_aiMouseEvents, sizeof(g_aiMouseEvents));
  SafeArrayUnaccessData( psaMtx );
  * ppsaMtx = psaMtx;

  return S_OK;
}

//==============================================================================
STDMETHODIMP CVMouse::GetDownEvents(SAFEARRAY ** ppsaMtx){
  SAFEARRAY *psaMtx;
  int * piData;

  * ppsaMtx = NULL;
  if( g_MakeSafeArray( 3, &psaMtx, &piData ) ){
    return g_ErrorToHresult(1);
  }
  piData[0] = g_aiMouseEvents[MOUSE_LEFT][MOUSE_DOWN];
  piData[1] = g_aiMouseEvents[MOUSE_MIDDLE][MOUSE_DOWN];  
  piData[2] = g_aiMouseEvents[MOUSE_RIGHT][MOUSE_DOWN];  
  SafeArrayUnaccessData( psaMtx );
  * ppsaMtx = psaMtx;

  return S_OK;
}

//==============================================================================
STDMETHODIMP CVMouse::GetUpEvents(SAFEARRAY ** ppsaMtx){
  SAFEARRAY *psaMtx;
  int * piData;

  * ppsaMtx = NULL;
  if( g_MakeSafeArray( 3, &psaMtx, &piData ) ){
    return g_ErrorToHresult(1);
  }
  piData[0] = g_aiMouseEvents[MOUSE_LEFT][MOUSE_UP];
  piData[1] = g_aiMouseEvents[MOUSE_MIDDLE][MOUSE_UP];  
  piData[2] = g_aiMouseEvents[MOUSE_RIGHT][MOUSE_UP];  
  SafeArrayUnaccessData( psaMtx );
  * ppsaMtx = psaMtx;
  
  return S_OK;
}

//==============================================================================
STDMETHODIMP CVMouse::GetDblclickEvents(SAFEARRAY ** ppsaMtx){
  SAFEARRAY *psaMtx;
  int * piData;

  * ppsaMtx = NULL;
  if( g_MakeSafeArray( 3, &psaMtx, &piData ) ){
    return g_ErrorToHresult(1);
  }
  piData[0] = g_aiMouseEvents[MOUSE_LEFT][MOUSE_DBLCLICK];
  piData[1] = g_aiMouseEvents[MOUSE_MIDDLE][MOUSE_DBLCLICK];  
  piData[2] = g_aiMouseEvents[MOUSE_RIGHT][MOUSE_DBLCLICK];
  SafeArrayUnaccessData( psaMtx );
  * ppsaMtx = psaMtx;

  return S_OK;
}

//==============================================================================
STDMETHODIMP CVMouse::ClearEvents(){
  int i,j;

  for(i=0;i<3;i++) {
    for(j=0;j<3;j++) g_aiMouseEvents[i][j]=0;
  }

  return S_OK;
}

//==============================================================================
STDMETHODIMP CVMouse::Show(){
  g_MouseCursorOn();
  return S_OK;
}

//==============================================================================
STDMETHODIMP CVMouse::Hide(){
  g_MouseCursorOff();
  return S_OK;
}

