#include "Shape/ring.h"
#include "Shape/circle.h"
#include "Shape/line.h"
#include "Shape/starField.h"
#include "Shape/starFieldCircle.h"
#include "Shape/magneticField.h"
#include "Shape/square.h"
#include "Shape/openSquare.h"
#include "Shape/displayText.h"

